### ISSUE TITLE
Substratum Requirement

### ISSUE THREAD

**Issue by moriel5** [jereksel/LibreSubstratum#172]
For some odd reason, LibreSubstratum tells me that Substratum is required to be installed for LibreSubstratum to work.
Isn't LibreSubstratum supposed to replace Substratum?

I am currently running cRDroid, Android 7.1.2, with full OMS support, on my Nexus 4.

**Comment by jereksel** [comment]
@moriel5 
Unfortunatelly due to the fact that interfacer requires substratum (to be honest it requires app that has id `project.substratum`): 

https://github.com/substratum/interfacer/blob/n-rootless/app/src/main/java/projekt/interfacer/services/JobService.java#L139 - `getSubsContext`
https://github.com/substratum/interfacer/blob/n-rootless/app/src/main/java/projekt/interfacer/services/JobService.java#L852

when Substratum is not installed Interfacer just crashes. In future I'm planning to create "mock" of substratum that would be installed by Libre, so Interfacer would work fine.

I hope I've explained this. If you have any questions feel free to ask.

**Comment by moriel5** [comment]
Thanks, that makes sense.
Although I am confused as to why we need another interfacer app, when we already have one preinstalled in the ROM, and we we just need a replacement for project.substratum.

**Comment by jereksel** [comment]
By mock, I meant mock of project.substratum, not interfacer.

**Comment by moriel5** [comment]
I am sorry for not being clear enough, I had meant that since there is already an interfacer app (projekt.interfacer), I do not understand why shouldn't LibreSubstratum instead pretend to be the official Substratum app and integrate with the existing utilities, rather than require an additional app to fulfill that purpose.

**Comment by jereksel** [comment]
Pretenting to be another app requires app that pretends to have the same id that the app it's pretending to be. Because of that not only I couldn't get Libre on play store (because id it already taken by Substratum), but I couldn't get on any store, because of id clash.

Frankly Interfacer wasn't really created to be used with app other than Substratum and that's where all these problems originate from.

**Comment by moriel5** [comment]
Ah. Thanks for the explanation.
In that case, I understand your reasoning and support it.
